
export const REMOVE_OBJECTIVE = 'REMOVE_OBJECTIVE';
export const REQUEST_ADD_OBJECTIVE = 'REQUEST_ADD_OBJECTIVE';
export const RECEIVE_ADD_OBJECTIVE = 'RECEIVE_ADD_OBJECTIVE';
export const REQUEST_DELETE_OBJECTIVE = 'REQUEST_DELETE_OBJECTIVE';
export const RECEIVE_DELETE_OBJECTIVE = 'RECEIVE_DELETE_OBJECTIVE';
export const INVALIDATE_OBJECTIVES_LIST = 'INVALIDATE_OBJECTIVES_LIST';
export const REQUEST_DATE_OBJECTIVES = 'REQUEST_DATE_OBJECTIVES';
export const RECEIVE_DATE_OBJECTIVES = 'RECEIVE_DATE_OBJECTIVES';
export const REQUEST_UPDATE_OBJECTIVE = 'REQUEST_UPDATE_OBJECTIVE';
export const RECEIVE_UPDATE_OBJECTIVE = 'RECEIVE_UPDATE_OBJECTIVE';
export const REQUEST_OBJECTIVES_SUMMARY = 'REQUEST_OBJECTIVES_SUMMARY';
export const RECEIVE_OBJECTIVES_SUMMARY = 'RECEIVE_OBJECTIVES_SUMMARY';
export const INVALIDATE_OBJECTIVES_SUMMARY = 'INVALIDATE_OBJECTIVES_SUMMARY';
export const REQUEST_OBJECTIVE_WORK_ENTRIES = 'REQUEST_OBJECTIVE_WORK_ENTRIES';
export const RECEIVE_OBJECTIVE_WORK_ENTRIES = 'RECEIVE_OBJECTIVE_WORK_ENTRIES';

export const DASHBOARD_SET_VISIBLE_DATE = 'DASHBOARD_SET_VISIBLE_DATE';

export const REQUEST_TASKS_LIST_PAGE = 'REQUEST_TASKS_LIST_PAGE';
export const RECEIVE_TASKS_LIST_PAGE = 'RECEIVE_TASKS_LIST_PAGE';
export const INVALIDATE_TASKS_LIST = 'INVALIDATE_TASKS_LIST';
export const REQUEST_ADD_TASK = 'REQUEST_ADD_TASK';
export const RECEIVE_ADD_TASK = 'RECEIVE_ADD_TASK';
export const CHANGE_VISIBLE_PAGE = 'CHANGE_VISIBLE_PAGE';
export const REQUEST_UPDATE_TASK = 'REQUEST_UPDATE_TASK';
export const RECEIVE_UPDATE_TASK = 'RECEIVE_UPDATE_TASK';
export const REQUEST_DELETE_TASK = 'REQUEST_DELETE_TASK';
export const RECEIVE_DELETE_TASK = 'RECEIVE_DELETE_TASK';
export const APPLY_TASKS_LIST_FILTERS = 'APPLY_TASKS_LIST_FILTERS';

export const REQUEST_LATEST_ACTIVITY_LIST_PAGE = 'REQUEST_LATEST_ACTIVITY_LIST_PAGE';
export const RECEIVE_LATEST_ACTIVITY_LIST_PAGE = 'RECEIVE_LATEST_ACTIVITY_LIST_PAGE';
export const INVALIDATE_LATEST_ACTIVITY = 'INVALIDATE_LATEST_ACTIVITY';

export const REQUEST_USERS_LIST = 'REQUEST_USERS_LIST';
export const RECEIVE_USERS_LIST = 'RECEIVE_USERS_LIST';
export const REQUEST_USER_AUTH = 'REQUEST_USER_AUTH';
export const RECEIVE_USER_AUTH = 'RECEIVE_USER_AUTH';

export const REQUEST_PROJECTS_LIST = 'REQUEST_PROJECTS_LIST';
export const RECEIVE_PROJECTS_LIST = 'RECEIVE_PROJECTS_LIST';

export const ADD_ERROR = 'ADD_ERROR';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const DISMISS_MESSAGE = 'DISMISS_MESSAGE';

export const REQUEST_GET_INTEGRATIONS = 'REQUEST_GET_INTEGRATIONS';
export const RECEIVE_GET_INTEGRATIONS = 'RECEIVE_GET_INTEGRATIONS';