
export const SET_AFTER_LOGIN_REDIRECTION = 'SET_AFTER_LOGIN_REDIRECTION';

export const REMOVE_OBJECTIVE = 'REMOVE_OBJECTIVE';
export const REQUEST_ADD_OBJECTIVE = 'REQUEST_ADD_OBJECTIVE';
export const RECEIVE_ADD_OBJECTIVE = 'RECEIVE_ADD_OBJECTIVE';
export const REQUEST_DELETE_OBJECTIVE = 'REQUEST_DELETE_OBJECTIVE';
export const RECEIVE_DELETE_OBJECTIVE = 'RECEIVE_DELETE_OBJECTIVE';
export const INVALIDATE_OBJECTIVES_LIST = 'INVALIDATE_OBJECTIVES_LIST';
export const REQUEST_DATE_OBJECTIVES = 'REQUEST_DATE_OBJECTIVES';
export const RECEIVE_DATE_OBJECTIVES = 'RECEIVE_DATE_OBJECTIVES';
export const REQUEST_UPDATE_OBJECTIVE = 'REQUEST_UPDATE_OBJECTIVE';
export const RECEIVE_UPDATE_OBJECTIVE = 'RECEIVE_UPDATE_OBJECTIVE';
export const REQUEST_OBJECTIVES_SUMMARY = 'REQUEST_OBJECTIVES_SUMMARY';
export const RECEIVE_OBJECTIVES_SUMMARY = 'RECEIVE_OBJECTIVES_SUMMARY';
export const INVALIDATE_OBJECTIVES_SUMMARY = 'INVALIDATE_OBJECTIVES_SUMMARY';
export const REQUEST_OBJECTIVE_WORK_ENTRIES = 'REQUEST_OBJECTIVE_WORK_ENTRIES';
export const RECEIVE_OBJECTIVE_WORK_ENTRIES = 'RECEIVE_OBJECTIVE_WORK_ENTRIES';
export const REQUEST_ADD_OBJECTIVE_WORK_ENTRY = 'REQUEST_ADD_OBJECTIVE_WORK_ENTRY';
export const RECEIVE_ADD_OBJECTIVE_WORK_ENTRY = 'RECEIVE_ADD_OBJECTIVE_WORK_ENTRY';
export const REQUEST_QUERY_OBJECTIVES = 'REQUEST_QUERY_OBJECTIVES';
export const RECEIVE_QUERY_OBJECTIVES = 'RECEIVE_QUERY_OBJECTIVES';
export const INVALIDATE_OBJECTIVE_WORK_ENTRIES = 'INVALIDATE_OBJECTIVE_WORK_ENTRIES';
export const REQUEST_SINGLE_OBJECTIVE = 'REQUEST_SINGLE_OBJECTIVE';
export const RECEIVE_SINGLE_OBJECTIVE = 'RECEIVE_SINGLE_OBJECTIVE';

export const DASHBOARD_SET_VISIBLE_DATE = 'DASHBOARD_SET_VISIBLE_DATE';
export const OVERVIEW_SET_VISIBLE_DATE = 'OVERVIEW_SET_VISIBLE_DATE';
export const REQUEST_MONTHLY_OVERVIEW = 'REQUEST_MONTHLY_OVERVIEW';
export const RECEIVE_MONTHLY_OVERVIEW = 'RECEIVE_MONTHLY_OVERVIEW';
export const INVALIDATE_MONTHLY_OVERVIEW = 'INVALIDATE_MONTHLY_OVERVIEW';

export const REQUEST_TASKS_LIST_PAGE = 'REQUEST_TASKS_LIST_PAGE';
export const RECEIVE_TASKS_LIST_PAGE = 'RECEIVE_TASKS_LIST_PAGE';
export const INVALIDATE_TASKS_LIST = 'INVALIDATE_TASKS_LIST';
export const REQUEST_ADD_TASK = 'REQUEST_ADD_TASK';
export const RECEIVE_ADD_TASK = 'RECEIVE_ADD_TASK';
export const CHANGE_VISIBLE_PAGE = 'CHANGE_VISIBLE_PAGE';
export const REQUEST_UPDATE_TASK = 'REQUEST_UPDATE_TASK';
export const RECEIVE_UPDATE_TASK = 'RECEIVE_UPDATE_TASK';
export const REQUEST_DELETE_TASK = 'REQUEST_DELETE_TASK';
export const RECEIVE_DELETE_TASK = 'RECEIVE_DELETE_TASK';
export const APPLY_TASKS_LIST_FILTERS = 'APPLY_TASKS_LIST_FILTERS';

export const REQUEST_LATEST_ACTIVITY_LIST_PAGE = 'REQUEST_LATEST_ACTIVITY_LIST_PAGE';
export const RECEIVE_LATEST_ACTIVITY_LIST_PAGE = 'RECEIVE_LATEST_ACTIVITY_LIST_PAGE';
export const INVALIDATE_LATEST_ACTIVITY = 'INVALIDATE_LATEST_ACTIVITY';

export const REQUEST_USERS_LIST = 'REQUEST_USERS_LIST';
export const RECEIVE_USERS_LIST = 'RECEIVE_USERS_LIST';
export const REQUEST_USER_AUTH = 'REQUEST_USER_AUTH';
export const RECEIVE_USER_AUTH = 'RECEIVE_USER_AUTH';
export const REQUEST_UPDATE_USER = 'REQUEST_UPDATE_USER';
export const RECEIVE_UPDATE_USER = 'RECEIVE_UPDATE_USER';
export const REQUEST_ADD_USER = 'REQUEST_ADD_USER';
export const RECEIVE_ADD_USER = 'RECEIVE_ADD_USER';
export const REQUEST_DELETE_USER = 'REQUEST_DELETE_USER';
export const RECEIVE_DELETE_USER = 'RECEIVE_DELETE_USER';
export const INVALIDATE_USERS_CACHE = 'INVALIDATE_USERS_CACHE';

export const REQUEST_PROJECTS_LIST = 'REQUEST_PROJECTS_LIST';
export const RECEIVE_PROJECTS_LIST = 'RECEIVE_PROJECTS_LIST';
export const REQUEST_ADD_PROJECT = 'REQUEST_ADD_PROJECT';
export const RECEIVE_ADD_PROJECT = 'RECEIVE_ADD_PROJECT';
export const REQUEST_UPDATE_PROJECT = 'REQUEST_UPDATE_PROJECT';
export const RECEIVE_UPDATE_PROJECT = 'RECEIVE_UPDATE_PROJECT';
export const REQUEST_DELETE_PROJECT = 'REQUEST_DELETE_PROJECT';
export const RECEIVE_DELETE_PROJECT = 'RECEIVE_DELETE_PROJECT';
export const INVALIDATE_PROJECTS_CACHE = 'INVALIDATE_PROJECTS_CACHE';
export const PROJECT_DASHBOARD_SET_VISIBLE_PROJECT = 'PROJECT_DASHBOARD_SET_VISIBLE_PROJECT';
export const INVALIDATE_PROJECT_DASHBOARD = 'INVALIDATE_PROJECT_DASHBOARD';
export const REQUEST_PROJECT_WORK_ENTRIES = 'REQUEST_PROJECT_WORK_ENTRIES';
export const RECEIVE_PROJECT_WORK_ENTRIES = 'RECEIVE_PROJECT_WORK_ENTRIES';
export const SET_PROJECT_DASHBOARD_WORK_ENTRIES_FILTER = 'SET_PROJECT_DASHBOARD_WORK_ENTRIES_FILTER';
export const SET_PROJECT_DASHBOARD_OBJECTIVES_FILTER = 'SET_PROJECT_DASHBOARD_OBJECTIVES_FILTER';

export const REQUEST_USER_WORK_ENTRIES = 'REQUEST_USER_WORK_ENTRIES';
export const RECEIVE_USER_WORK_ENTRIES = 'RECEIVE_USER_WORK_ENTRIES';
export const SET_PROFILE_WORK_ENTRIES_FILTERS = 'SET_PROFILE_WORK_ENTRIES_FILTERS';

export const ADD_ERROR = 'ADD_ERROR';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const DISMISS_MESSAGE = 'DISMISS_MESSAGE';

export const REQUEST_GET_INTEGRATIONS = 'REQUEST_GET_INTEGRATIONS';
export const RECEIVE_GET_INTEGRATIONS = 'RECEIVE_GET_INTEGRATIONS';
export const REQUEST_UPDATE_INTEGRATION = 'REQUEST_UPDATE_INTEGRATION';
export const RECEIVE_UPDATE_INTEGRATION = 'RECEIVE_UPDATE_INTEGRATION';
export const INVALIDATE_INTEGRATIONS_LIST = 'INVALIDATE_INTEGRATIONS_LIST';
export const REQUEST_DELETE_INTEGRATION = 'REQUEST_DELETE_INTEGRATION';
export const RECEIVE_DELETE_INTEGRATION = 'RECEIVE_DELETE_INTEGRATION';
export const REQUEST_CREATE_INTEGRATION = 'REQUEST_CREATE_INTEGRATION';
export const RECEIVE_CREATE_INTEGRATION = 'RECEIVE_CREATE_INTEGRATION';

export const REQUEST_GET_ALARMS = 'REQUEST_GET_ALARMS';
export const RECEIVE_GET_ALARMS = 'RECEIVE_GET_ALARMS';
export const REQUEST_CREATE_ALARM = 'REQUEST_CREATE_ALARM';
export const RECEIVE_CREATE_ALARM = 'RECEIVE_CREATE_ALARM';
export const REQUEST_UPDATE_ALARM = 'REQUEST_UPDATE_ALARM';
export const RECEIVE_UPDATE_ALARM = 'RECEIVE_UPDATE_ALARM';
export const REQUEST_DELETE_ALARM = 'REQUEST_DELETE_ALARM';
export const RECEIVE_DELETE_ALARM = 'RECEIVE_DELETE_ALARM';
export const INVALIDATE_ALARMS_LIST = 'INVALIDATE_ALARMS_LIST';

export const INVALIDATE_PROJECTS_BILLING = 'INVALIDATE_PROJECTS_BILLING';
export const REQUEST_PROJECTS_BILLING = 'REQUEST_PROJECTS_BILLING';
export const RECEIVE_PROJECTS_BILLING = 'RECEIVE_PROJECTS_BILLING';
export const REQUEST_ADD_INVOICE = 'REQUEST_ADD_INVOICE';
export const RECEIVE_ADD_INVOICE = 'RECEIVE_ADD_INVOICE';
export const REQUEST_UPDATE_INVOICE = 'REQUEST_UPDATE_INVOICE';
export const RECEIVE_UPDATE_INVOICE = 'RECEIVE_UPDATE_INVOICE';
export const REQUEST_DELETE_INVOICE = 'REQUEST_DELETE_INVOICE';
export const RECEIVE_DELETE_INVOICE = 'RECEIVE_DELETE_INVOICE';
export const REQUEST_INVOICES_LIST = 'REQUEST_INVOICES_LIST';
export const RECEIVE_INVOICES_LIST = 'RECEIVE_INVOICES_LIST';
export const INVALIDATE_INVOICES_LIST = 'INVALIDATE_INVOICES_LIST';
