
export const REMOVE_OBJECTIVE = 'REMOVE_OBJECTIVE';
export const REQUEST_ADD_OBJECTIVE = 'REQUEST_ADD_OBJECTIVE';
export const RECEIVE_ADD_OBJECTIVE = 'RECEIVE_ADD_OBJECTIVE';
export const INVALIDATE_OBJECTIVES_LIST = 'INVALIDATE_OBJECTIVES_LIST';
export const REQUEST_DATE_OBJECTIVES = 'REQUEST_DATE_OBJECTIVES';
export const RECEIVE_DATE_OBJECTIVES = 'RECEIVE_DATE_OBJECTIVES';
export const REQUEST_UPDATE_OBJECTIVE = 'REQUEST_UPDATE_OBJECTIVE';
export const RECEIVE_UPDATE_OBJECTIVE = 'RECEIVE_UPDATE_OBJECTIVE';

export const DASHBOARD_SET_VISIBLE_DATE = 'DASHBOARD_SET_VISIBLE_DATE';

export const REQUEST_TASKS_LIST_PAGE = 'REQUEST_TASKS_LIST_PAGE';
export const RECEIVE_TASKS_LIST_PAGE = 'RECEIVE_TASKS_LIST_PAGE';
export const INVALIDATE_TASKS_LIST = 'INVALIDATE_TASKS_LIST';
export const REQUEST_ADD_TASK = 'REQUEST_ADD_TASK';
export const RECEIVE_ADD_TASK = 'RECEIVE_ADD_TASK';

export const REQUEST_LATEST_ACTIVITY_LIST_PAGE = 'REQUEST_LATEST_ACTIVITY_LIST_PAGE';
export const RECEIVE_LATEST_ACTIVITY_LIST_PAGE = 'RECEIVE_LATEST_ACTIVITY_LIST_PAGE';
export const INVALIDATE_LATEST_ACTIVITY = 'INVALIDATE_LATEST_ACTIVITY';